// <auto-generated />
using ColombianCoffeeApp.src.Shared.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColombianCoffeeApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250810034046_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ColombianCoffeeApp.src.Modules.Usuarios.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .HasColumnType("longtext");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("longtext");

                    b.Property<string>("Rol")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ColombianCoffeeApp.src.Modules.Variedades.Domain.Entities.VariedadCafe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AltitudOptima")
                        .HasColumnType("int");

                    b.Property<string>("CalidadGrano")
                        .HasColumnType("longtext");

                    b.Property<string>("DensidadSiembra")
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Familia")
                        .HasColumnType("longtext");

                    b.Property<string>("GrupoGenetico")
                        .HasColumnType("longtext");

                    b.Property<string>("Historia")
                        .HasColumnType("longtext");

                    b.Property<string>("NombreCientifico")
                        .HasColumnType("longtext");

                    b.Property<string>("NombreComun")
                        .HasColumnType("longtext");

                    b.Property<string>("Obtentor")
                        .HasColumnType("longtext");

                    b.Property<string>("Porte")
                        .HasColumnType("longtext");

                    b.Property<string>("RecomendacionNutricion")
                        .HasColumnType("longtext");

                    b.Property<string>("Rendimiento")
                        .HasColumnType("longtext");

                    b.Property<string>("ResistenciaAntracnosis")
                        .HasColumnType("longtext");

                    b.Property<string>("ResistenciaNematodos")
                        .HasColumnType("longtext");

                    b.Property<string>("ResistenciaRoya")
                        .HasColumnType("longtext");

                    b.Property<string>("RutaImagen")
                        .HasColumnType("longtext");

                    b.Property<string>("TamanoGrano")
                        .HasColumnType("longtext");

                    b.Property<string>("TiempoCosecha")
                        .HasColumnType("longtext");

                    b.Property<string>("TiempoMaduracion")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Variedades");
                });
#pragma warning restore 612, 618
        }
    }
}
