// <auto-generated />
using ColombianCoffeeApp.src.Shared.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColombianCoffeeApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ColombianCoffeeApp.src.Modules.Usuarios.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("ColombianCoffeeApp.src.Modules.Variedades.Domain.Entities.VariedadCafe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AltitudOptima")
                        .HasColumnType("int");

                    b.Property<int>("CalidadGrano")
                        .HasColumnType("int");

                    b.Property<string>("DensidadSiembra")
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Familia")
                        .HasColumnType("longtext");

                    b.Property<string>("GrupoGenetico")
                        .HasColumnType("longtext");

                    b.Property<string>("Historia")
                        .HasColumnType("longtext");

                    b.Property<string>("NombreCientifico")
                        .HasColumnType("longtext");

                    b.Property<string>("NombreComun")
                        .HasColumnType("longtext");

                    b.Property<string>("Obtentor")
                        .HasColumnType("longtext");

                    b.Property<int>("Porte")
                        .HasColumnType("int");

                    b.Property<string>("RecomendacionNutricion")
                        .HasColumnType("longtext");

                    b.Property<int>("Rendimiento")
                        .HasColumnType("int");

                    b.Property<int>("ResistenciaAntracnosis")
                        .HasColumnType("int");

                    b.Property<int>("ResistenciaNematodos")
                        .HasColumnType("int");

                    b.Property<int>("ResistenciaRoya")
                        .HasColumnType("int");

                    b.Property<string>("RutaImagen")
                        .HasColumnType("longtext");

                    b.Property<int>("TamanoGrano")
                        .HasColumnType("int");

                    b.Property<string>("TiempoCosecha")
                        .HasColumnType("longtext");

                    b.Property<string>("TiempoMaduracion")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("variedad", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
